# This is a simple workflow to check that all modified files satisfy code
# quality requirements
name: Code quality

# Controls when the workflow will run
on:
  # Triggers the workflow on push and PRs
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  pre-commit:
    name: Code formatting
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Format code with black
        run: |
          pip install black
          black .
